import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/common/styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import antdGlobalTheme from "@/common/styles/antdThemeConfig";
import { getPageTitle } from "@/common/utils/getPageTitle";
import ApolloClientProvider from "@/apollo/apollo-client-provider";
import AuthGuard from "@/common/components/auth-guard";
import { GlobalsProvider } from "@/common/context/globals";
import { IS_PROD } from "@/common/constants/global";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: getPageTitle("Create Next App"),
  description: "Generated by create next app",
  robots: {
    index: IS_PROD,
    follow: IS_PROD,
    googleBot: {
      index: IS_PROD,
      follow: IS_PROD,
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider theme={antdGlobalTheme}>
        {/* TODO: Extract server side Apollo config */}
        <ApolloClientProvider>
          <GlobalsProvider>
            <AuthGuard>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                <AntdRegistry>{children}</AntdRegistry>
              </body>
            </AuthGuard>
          </GlobalsProvider>
        </ApolloClientProvider>
      </ConfigProvider>
    </html>
  );
}
