#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Testing the build before committing'

yarn test-all ||
(
    echo '\n\n❌👷🔨❌ Build Failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)

echo '✅✅✅✅ Production build successful ✅✅✅✅'
